# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DJabberd
version:      0.81
version_from: lib/DJabberd.pm
installdirs:  site
requires:
    Danga::Socket:                 1.51
    Digest::HMAC_SHA1:             0
    Log::Log4perl:                 0
    Net::DNS:                      0.48
    Net::SSLeay:                   0
    XML::LibXML::SAX:              0
    XML::SAX:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
